import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: ['src/openai/chat.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/openai',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/openai/completion.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/openai',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/openai/embedding.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/openai',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/azure-openai/chat.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/azure-openai',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/google/generate-content.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/google',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/anthropic/completion.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/anthropic',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/cohere/generation.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/cohere',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/cohere/embedding.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/cohere',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/ollama/generation.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/ollama',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/ollama/embedding.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/ollama',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/huggingface/text-generation.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/huggingface',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/togetherai/inference.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/togetherai',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/react/index.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/react',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/node/index.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/node',
    external: [/^@axflow\/models\//],
    dts: true,
  },
  {
    entry: ['src/shared/index.ts'],
    format: ['cjs', 'esm'],
    outDir: 'dist/shared',
    external: [/^@axflow\/models\//],
    dts: true,
  },
]);
